### ISSUE TITLE
Choi Matrix for Depolarizing Channel

### ISSUE THREAD

**Issue by vprusso** [nathanieljohnston/QETLAB#18]
It seems as if the `ChoiMatrix` function may be performing a slightly off conversion for certain cases when the input to the function is a set of Kraus operators.

For instance:

```
% The Choi matrix of the depolarizing channel on two-dimensions.
full(DepolarizingChannel(2))
ans =

    0.5000         0         0         0
         0    0.5000         0         0
         0         0    0.5000         0
         0         0         0    0.5000

% Obtain the Kraus operators corresponding to the depolarizing channel.
kraus_ops = KrausOperators(DepolarizingChannel(2));

T = {kraus_ops{1}, kraus_ops{1}';  
       kraus_ops{2}, kraus_ops{2}';
       kraus_ops{3}, kraus_ops{3}';
       kraus_ops{4}, kraus_ops{4}';
};

% Compute the Choi matrix corresponding to the Kraus operators. I *believe* we should
% expect to get the Choi matrix of the depolarizing channel back, but instead, we get
% the following matrix.
ChoiMatrix(T)
ans =

    0.5000         0         0         0
         0         0    0.5000         0
         0    0.5000         0         0
         0         0         0    0.5000
```

I might be misinterpreting/misusing something, but just in case I am not, I figured I would mention that here.

**Comment by nathanieljohnston** [comment]
Ah, this is actually because (generalized) Kraus operators behave a bit differently than this (and I apologize, the documentation is not great about clarifying this point). If you provide both left- and right-Kraus operators then they are the A_i and B_i matrices in sum_i A_i X B_i^*. That is, you provide them *without* the conjugate transpose. So if you replace your middle block of code with either of

T = {kraus_ops{1}, kraus_ops{1};  
       kraus_ops{2}, kraus_ops{2};
       kraus_ops{3}, kraus_ops{3};
       kraus_ops{4}, kraus_ops{4};
};

or

T = {kraus_ops{1};
       kraus_ops{2};
       kraus_ops{3};
       kraus_ops{4};
};

then you'll get the right final answer.

**Comment by vprusso** [comment]
Ah, I figured it was "user-error" and something I was misinterpreting. I think the docs are written quite clearly, it was very much my own inability to parse them properly. Thank you all the same for the clarification and for the quick response! I'll go ahead and close this issue. Thanks again!
