### ISSUE TITLE
LocalDistinguishability fails with data hiding states 

### ISSUE THREAD

**Issue by cosenal** [nathanieljohnston/QETLAB#7]
Embarassingly enough the bug is in my own function :)
Check this script: https://gist.github.com/cosenal/65bfaec556e7d20855ea 
It should output 5/6, instead it outputs 1 (states are from http://arxiv.org/abs/quant-ph/0103098)
It probably fails in many other cases too.

@nathanieljohnston @vprusso Can you help me with debugging this?

**Comment by nathanieljohnston** [comment]
Actually, I'm even having trouble just with inputParser right now. When running the script, I get the following error:

    Undefined function 'addParameter' for input arguments of type 'inputParser'.
    
    Error in LocalDistinguishability (line 63)
    addParameter(parser, 'P', ones(1,num_ops)/num_ops, @isnumeric);

I get this in MATLAB 2011b as well as 2013a. Thoughts?

**Comment by cosenal** [comment]
I made another PR to fix that. Stupid MATLAB legacy issues. http://www.mathworks.com/help/matlab/ref/inputparser.addparamvalue.html
'Not recommended' (shrug)

**Comment by nathanieljohnston** [comment]
Thanks! The glitch is actually my fault -- in low-dimensional cases, the SymmetricExtension function did some simplifying stuff to speed up the script. However, that simplifying stuff assumed that the input state was positive semidefinite. Since your SDP never explicitly forced the measurements to be PSD, it was returning non-PSD "measurements" that gave higher values. I'll patch the SymmetricExtension function to fix this.

**Comment by nathanieljohnston** [comment]
Patch uploaded, and your code returns 5/6 now, as expected.

**Comment by cosenal** [comment]
Should I add an extra-constraint to check that the measurement operators are positive? or the SymmetricExtension function takes care of it in all cases now?

**Comment by nathanieljohnston** [comment]
The SymmetricExtension function takes care of it in all cases now: you don't need to change your function at all.

**Comment by cosenal** [comment]
Ok, thanks!
